const KEY='b7a9f4e6b8634a9bbf95c7a84c2d3e71';
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const icons={pause:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M8 5v14M16 5v14"/></svg>',play:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="m8 5 11 7-11 7V5Z"/></svg>',folder:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M3 7h7l2 2h9v10H3V7Z"/></svg>',open:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M8 5H5v14h14v-3M12 5h7v7M19 5l-9 9"/></svg>',retry:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M20 7v5h-5M4 17v-5h5M6.1 8.3A7 7 0 0 1 18.5 10M17.9 15.7A7 7 0 0 1 5.5 14"/></svg>',x:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="m7 7 10 10M17 7 7 17"/></svg>',trash:'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor"><path d="M5 7h14M9 7V5h6v2m-8 0 1 12h8l1-12"/></svg>'};
let tasks=[],config=null,engines={},filter='all',query='',pendingRemoveId=null,settingsOpen=false;

async function api(path,opt={}){opt.headers={...(opt.headers||{}),'X-BoltDM-Key':KEY};if(opt.body)opt.headers['Content-Type']='application/json';const r=await fetch(path,opt);const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={error:text}}if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function fmtBytes(n){n=Number(n)||0;if(!n)return'0 B';const u=['B','KB','MB','GB','TB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return`${n.toFixed(i?1:0)} ${u[i]}`}
function fmtRate(n){return`${fmtBytes(n)}/s`}
function rateHTML(n){const txt=fmtRate(n).split(' ');return`${txt[0]} <span class="rateunit">${txt.slice(1).join(' ')}</span>`}
function eta(t){if(t.state!=='downloading'||!t.speedBytesPerSec||!t.size)return'—';let s=Math.max(0,(t.size-t.downloaded)/t.speedBytesPerSec);if(s<60)return`${Math.ceil(s)}s`;if(s<3600)return`${Math.ceil(s/60)}m`;return`${Math.floor(s/3600)}h ${Math.ceil((s%3600)/60)}m`}
function host(raw){try{const u=new URL(raw);return u.hostname||u.protocol.replace(':','')||raw}catch{return raw}}
function ext(name){const x=(name.split('.').pop()||'file').slice(0,4);return x===name?'file':x}
function speedLabel(v){return v?fmtRate(v):'Unlimited'}
function dirOf(path){const i=Math.max(String(path||'').lastIndexOf('/'),String(path||'').lastIndexOf('\\'));return i>=0?path.slice(0,i):path}
function toast(msg,bad=false){const d=document.createElement('div');d.className='toast'+(bad?' bad':'');d.textContent=msg;$('#toasts').appendChild(d);setTimeout(()=>d.remove(),3400)}
function modal(el,on){el.classList.toggle('open',on);$('#scrim').classList.toggle('open',on||settingsOpen)}
function filtered(){return tasks.filter(t=>{const f=filter==='all'||(filter==='active'&&t.state==='downloading')||(filter==='failed'&&['failed','canceled'].includes(t.state))||t.state===filter;const q=!query||`${t.filename} ${t.url} ${t.outputPath} ${t.engine||''} ${t.sourceKind||''}`.toLowerCase().includes(query);return f&&q})}
function counts(){const c={all:tasks.length,active:0,queued:0,completed:0,failed:0};for(const t of tasks){if(t.state==='downloading')c.active++;if(t.state==='queued')c.queued++;if(t.state==='completed')c.completed++;if(['failed','canceled'].includes(t.state))c.failed++}for(const[k,v]of Object.entries(c)){const e=$(`#c-${k}`);if(e)e.textContent=v}$('#m-active').textContent=c.active;$('#m-queued').textContent=c.queued;$('#m-completed').textContent=c.completed;$('#m-speed').innerHTML=rateHTML(tasks.reduce((a,t)=>a+(t.speedBytesPerSec||0),0))}
function taskActions(t){let left='';if(['downloading','queued'].includes(t.state))left=`<button class="action" data-act="pause" data-id="${t.id}" title="Pause">${icons.pause}</button>`;else if(['paused','failed','canceled'].includes(t.state))left=`<button class="action" data-act="resume" data-id="${t.id}" title="${t.state==='failed'?'Retry':'Resume'}">${t.state==='failed'?icons.retry:icons.play}</button>`;else if(t.state==='completed')left=`<button class="action" data-act="open" data-id="${t.id}" title="Open">${icons.open}</button>`;const stop=['downloading','queued','paused'].includes(t.state)?`<button class="action" data-act="cancel" data-id="${t.id}" title="Cancel download">${icons.x}</button>`:`<button class="action" data-act="remove" data-id="${t.id}" title="Remove">${icons.trash}</button>`;return`${left}<button class="action" data-act="reveal" data-id="${t.id}" title="Show in folder">${icons.folder}</button>${stop}`}
function engineLabel(t){const e=t.engine||'native',s=t.sourceKind||'direct';return`${e} · ${s}`}
function render(){counts();const visible=filtered(),list=$('#list');if(!visible.length){const copy=query?'No downloads match your search.':filter==='all'?'There are no downloads yet. Use the Chrome extension or start a download here.':'Nothing in this section.';list.innerHTML=`<div class="empty"><div class="emptybox"><div class="empty-orbit"></div><h2>${query?'No match':'No downloads'}</h2><p>${copy}</p>${filter==='all'&&!query?'<button class="btn gold" id="emptyAdd">New download</button>':''}</div></div>`;$('#emptyAdd')?.addEventListener('click',openAdd);return}list.innerHTML=visible.map(t=>{const p=Math.max(0,Math.min(100,t.progress||0));const seg=t.segments||t.segmentSetting||config?.segmentsPerFile||1,conn=t.connections||t.connectionSetting||config?.connectionsPerFile||1;return`<div class="row" data-id="${t.id}"><div class="file"><div class="fileicon">${esc(ext(t.filename))}</div><div><div class="filename" title="${esc(t.outputPath||t.filename)}">${esc(t.filename)}</div><div class="filemeta"><span class="host">${esc(host(t.url))}</span><span>${esc(engineLabel(t))}</span></div><div class="progressline"><i style="width:${p}%"></i></div>${t.error?`<div class="err" title="${esc(t.error)}">${esc(t.error)}</div>`:''}</div></div><div><div class="state ${t.state}">${esc(t.state)}</div><div class="subval">${p.toFixed(1)}%</div></div><div class="col-speed"><div class="value">${t.state==='downloading'?fmtRate(t.speedBytesPerSec):'—'}</div><div class="subval">ETA ${eta(t)}${t.uploadSpeedBytesPerSec?` · ↑ ${fmtRate(t.uploadSpeedBytesPerSec)}`:''}</div></div><div class="col-size"><div class="value">${fmtBytes(t.downloaded)}</div><div class="subval">of ${t.size?fmtBytes(t.size):'unknown'}${t.files?.length>1?` · ${t.files.length} files`:''}</div></div><div class="col-segments"><div class="value">${seg} seg · ${conn} conn</div><div class="subval">${esc(engineLabel(t))}</div></div><div class="actions">${taskActions(t)}</div></div>`}).join('')}
