function ensureAddOptions(){if($('#addAdvanced'))return;const body=$('#addModal .modalbody');const box=document.createElement('div');box.id='addAdvanced';box.innerHTML=`<div class="grid2"><div class="field"><label>Transfer engine</label><select class="select" id="addEngine"><option value="auto">Auto</option><option value="native">Native HTTP/HTTPS</option><option value="aria2">aria2</option></select><div class="hint" id="addEngineHint">Auto keeps normal HTTP/HTTPS on BoltDM and routes supported extra protocols to aria2.</div></div><div class="field"><label>Start time</label><input class="input" id="addStartAt" type="datetime-local"><div class="hint">Leave empty to start as soon as a queue slot is available.</div></div></div><div class="field"><label>Optional checksum</label><div class="grid2" style="grid-template-columns:120px 1fr"><select class="select" id="addChecksumAlgorithm"><option value="sha256">SHA-256</option><option value="sha512">SHA-512</option><option value="sha1">SHA-1</option><option value="md5">MD5</option></select><input class="input" id="addChecksum" autocomplete="off" spellcheck="false" placeholder="Expected hexadecimal digest"></div><div class="hint">BoltDM verifies a single-file result before marking the task completed.</div></div>`;body.appendChild(box);$('#addUrl').placeholder='https://…  ftp://…  sftp://…  magnet:?…'}
ensureAddOptions();
renderPresetButtons($('#speedPresets'));
$('#nav').addEventListener('click',e=>{const b=e.target.closest('[data-filter]');if(!b)return;filter=b.dataset.filter;$$('.navbtn[data-filter]').forEach(x=>x.classList.toggle('active',x===b));const names={all:['All downloads','DOWNLOAD LIST'],active:['Active downloads','ACTIVE CONNECTIONS'],queued:['Queued','WAITING'],completed:['Completed','DOWNLOAD HISTORY'],failed:['Attention','FAILED OR CANCELED']};$('#viewTitle').textContent=names[filter][0];$('#viewSub').textContent=names[filter][1];render()});
$('#search').addEventListener('input',e=>{query=e.target.value.trim().toLowerCase();render()});
$('#list').addEventListener('click',e=>{const b=e.target.closest('[data-act]');if(b)action(b.dataset.id,b.dataset.act)});
$('#addBtn').onclick=openAdd;$('#pauseAll').onclick=()=>bulk('pause','Paused');$('#resumeAll').onclick=()=>bulk('resume','Resumed');$('#moreBulk').onclick=()=>modal($('#bulkModal'),true);$('#retryFailed').onclick=()=>{modal($('#bulkModal'),false);bulk('retry-failed','Retried')};$('#clearCompleted').onclick=()=>{modal($('#bulkModal'),false);bulk('clear-completed','Cleared')};$('#cancelAll').onclick=()=>{modal($('#bulkModal'),false);bulk('cancel','Canceled')};
async function confirmRemove(deleteFiles){if(!pendingRemoveId)return;try{await api(`/api/v1/tasks/${pendingRemoveId}/remove?deleteFiles=${deleteFiles}`,{method:'POST'});pendingRemoveId=null;modal($('#removeModal'),false);toast(deleteFiles?'File deleted and download removed':'Download removed from history');await refresh()}catch(e){toast(e.message,true)}}
$('#removeKeep').onclick=()=>confirmRemove(false);$('#removeDelete').onclick=()=>confirmRemove(true);
$('#confirmAdd').onclick=async()=>{const url=$('#addUrl').value.trim();if(!url)return toast('Enter a URL',true);const digest=$('#addChecksum').value.trim();let startAt;const scheduled=$('#addStartAt').value;if(scheduled){const d=new Date(scheduled);if(Number.isNaN(d.getTime()))return toast('Enter a valid start time',true);startAt=d.toISOString()}const request={url,downloadDir:$('#addDir').value.trim(),engine:$('#addEngine').value||'auto'};if(startAt)request.startAt=startAt;if(digest)request.checksum={algorithm:$('#addChecksumAlgorithm').value,digest};try{await api('/api/v1/downloads',{method:'POST',body:JSON.stringify({downloads:[request]})});modal($('#addModal'),false);toast(startAt?'Download scheduled':'Download added');await refresh()}catch(e){toast(e.message,true)}};$('#addUrl').addEventListener('keydown',e=>{if(e.key==='Enter')$('#confirmAdd').click()});
$('#pickAddDir').onclick=()=>pickDir($('#addDir'));$('#pickSetDir').onclick=()=>pickDir($('#setDir'));const openDownloads=async()=>{try{await api('/api/v1/system/open-downloads',{method:'POST'})}catch(e){toast(e.message,true)}};$('#openFolder').onclick=$('#openFolder2').onclick=$('#openFolder3').onclick=openDownloads;
$('#settingsBtn').onclick=()=>{settingsOpen=true;populateSettings();$('#scrim').classList.add('open');$('#settingsDrawer').classList.add('open')};$('#closeSettings').onclick=closePanels;$('#saveSettings').onclick=async()=>{if(await saveSettings())closePanels(false)};$('#resetSpeed').onclick=()=>{$('#setSpeed').value=0};$('#quitApp').onclick=async()=>{try{await api('/api/v1/system/shutdown',{method:'POST'});toast('BoltDM is shutting down');setTimeout(()=>window.close(),350)}catch(e){toast(e.message,true)}};
$('#settingsTabs').addEventListener('click',e=>{const b=e.target.closest('[data-stab]');if(!b)return;$$('.stab').forEach(x=>x.classList.toggle('active',x===b));$$('.settings-panel').forEach(x=>x.classList.toggle('active',x.dataset.spanel===b.dataset.stab))});
$('#locationList').addEventListener('click',e=>{const b=e.target.closest('[data-move-id]');if(b)moveTask(b.dataset.moveId)});$('#tuningList').addEventListener('click',e=>{const b=e.target.closest('[data-tune-apply]');if(b)tuneTask(b.dataset.tuneApply,b.closest('[data-tune-row]'))});
$('#moveIncompleteDefault').onclick=async()=>{const destination=$('#setDir').value.trim()||config.downloadDir;const list=tasks.filter(t=>t.state!=='completed'&&(!t.engine||t.engine==='native'));if(!list.length)return toast('No movable incomplete native downloads');if(!confirm(`Move ${list.length} incomplete download${list.length===1?'':'s'} to\n${destination}?`))return;let ok=0;for(const t of list){try{await api(`/api/v1/tasks/${t.id}/move`,{method:'POST',body:JSON.stringify({destination})});ok++}catch(e){toast(`${t.filename}: ${e.message}`,true)}}toast(`Moved ${ok} download${ok===1?'':'s'}`);await refresh()};
$('#speedBtn').onclick=e=>{e.stopPropagation();$('#speedPop').classList.toggle('open')};$('#speedPresets').onclick=e=>{const b=e.target.closest('.preset');if(b){saveSpeedLimit(Number(b.dataset.speed));$('#speedPop').classList.remove('open')}};$('#speedQuickApply').onclick=()=>{const v=Math.max(0,Number($('#speedQuick').value)||0)*(Number($('#speedQuickUnit').value)||1048576);saveSpeedLimit(v);$('#speedPop').classList.remove('open')};$('#speedQuick').addEventListener('keydown',e=>{if(e.key==='Enter')$('#speedQuickApply'].click()});document.addEventListener('click',e=>{if(!e.target.closest('#speedPop')&&!e.target.closest('#speedBtn'))$('#speedPop').classList.remove('open')});
$('#applyEngineActive').onclick=async()=>{if(await saveSettings())await bulk('restart-active','Reconfigured')};
$('#settingsSpeedPresets').addEventListener('click',e=>{const b=e.target.closest('.preset');if(!b)return;const bytes=Number(b.dataset.speed),unit=Number($('#setSpeedUnit').value)||1048576;$('#setSpeed').value=bytes?bytes/unit:0;$$('#settingsSpeedPresets .preset').forEach(x=>x.classList.toggle('active',x===b))});
$('#setFontSizeRange').addEventListener('input',()=>{$('#setFontSize').value=$('#setFontSizeRange').value});$('#setFontSize').addEventListener('input',()=>{$('#setFontSizeRange').value=$('#setFontSize').value});$('#previewAppearance').onclick=()=>applyAppearance(appearanceFromUI());$('#resetAppearance').onclick=()=>{const d={fontFamily:'"Segoe UI Variable","Segoe UI",Inter,system-ui,sans-serif',fontSizePercent:100,fontWeight:400,fontStyle:'normal',density:'balanced',accentColor:'#c9a46a',backgroundColor:'#070708',surfaceColor:'#0e0e11',textColor:'#f2efe8',cornerRadius:14,reduceMotion:false,customCSS:''};$('#setFontFamily').value=d.fontFamily;$('#setFontSize').value=$('#setFontSizeRange').value=100;$('#setFontWeight').value='400';$('#setFontStyle').value='normal';$('#setDensity').value='balanced';$('#setAccent').value=d.accentColor;$('#setBackground').value=d.backgroundColor;$('#setSurface').value=d.surfaceColor;$('#setTextColor').value=d.textColor;$('#setRadius').value=14;$('#setReduceMotion').checked=false;$('#setCustomCSS').value='';applyAppearance(d)};
function closePanels(revert=true){modal($('#addModal'),false);modal($('#bulkModal'),false);modal($('#removeModal'),false);$('#settingsDrawer').classList.remove('open');settingsOpen=false;$('#scrim').classList.remove('open');if(revert&&config)applyAppearance(config.appearance||{})}$$('[data-close]').forEach(b=>b.onclick=()=>closePanels());$('#scrim').onclick=()=>closePanels();document.addEventListener('keydown',e=>{if(e.key==='Escape')closePanels();if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='n'){e.preventDefault();openAdd()}});
setInterval(refresh,850);refresh();
