function mixHex(a,b,t){const n=x=>parseInt(x,16);const h=x=>Math.round(x).toString(16).padStart(2,'0');if(!/^#[0-9a-f]{6}$/i.test(a)||!/^#[0-9a-f]{6}$/i.test(b))return a;return'#'+[1,3,5].map(i=>h(n(a.slice(i,i+2))*(1-t)+n(b.slice(i,i+2))*t)).join('')}
function applyAppearance(a={}){const r=document.documentElement.style,accent=a.accentColor||'#c9a46a';r.setProperty('--font-family',a.fontFamily||'"Segoe UI Variable","Segoe UI",Inter,system-ui,sans-serif');r.setProperty('--font-scale',String((Number(a.fontSizePercent)||100)/100));r.setProperty('--font-style',a.fontStyle==='italic'?'italic':'normal');r.setProperty('--base-weight',String(Number(a.fontWeight)||400));r.setProperty('--gold',accent);r.setProperty('--gold2',mixHex(accent,'#ffffff',.28));r.setProperty('--gold-dim',mixHex(accent,'#000000',.45));r.setProperty('--bg',a.backgroundColor||'#070708');r.setProperty('--panel',a.surfaceColor||'#0e0e11');r.setProperty('--text',a.textColor||'#f2efe8');r.setProperty('--radius',`${Number(a.cornerRadius)||14}px`);r.setProperty('--row-height',a.density==='compact'?'62px':a.density==='spacious'?'88px':'75px');$('#customUserCSS').textContent=a.customCSS||'';let ms=$('#motionStyle');if(!ms){ms=document.createElement('style');ms.id='motionStyle';document.head.appendChild(ms)}ms.textContent=a.reduceMotion?'*,*::before,*::after{animation-duration:.001ms!important;animation-iteration-count:1!important;transition-duration:.001ms!important;scroll-behavior:auto!important}':''}
function runtimeConfigUI(){if(!config)return;$('#speedBtnText').textContent=speedLabel(config.speedLimitBytesPerSec);$('#speedCurrent').textContent=speedLabel(config.speedLimitBytesPerSec);$$('#speedPresets .preset').forEach(b=>b.classList.toggle('active',Number(b.dataset.speed)===Number(config.speedLimitBytesPerSec||0)));if(!settingsOpen)applyAppearance(config.appearance||{})}
function appearanceFromUI(){return{fontFamily:$('#setFontFamily').value.trim(),fontSizePercent:Number($('#setFontSize').value)||100,fontWeight:Number($('#setFontWeight').value)||400,fontStyle:$('#setFontStyle').value,density:$('#setDensity').value,accentColor:$('#setAccent').value,backgroundColor:$('#setBackground').value,surfaceColor:$('#setSurface').value,textColor:$('#setTextColor').value,cornerRadius:Number($('#setRadius').value)||14,reduceMotion:$('#setReduceMotion').checked,customCSS:$('#setCustomCSS').value}}
function populateSettings(){if(!config)return;$('#setLaunch').value=config.launchMode||'dashboard';$('#setDir').value=config.downloadDir||'';$('#setActive').value=config.maxActive||3;$('#setHost').value=config.maxPerHost||2;$('#setSegments').value=config.segmentsPerFile||8;$('#setConnections').value=config.connectionsPerFile||4;$('#setRetries').value=config.retries||6;const minUnit=1048576;$('#setMinSegmentUnit').value=String(minUnit);$('#setMinSegment').value=((config.minSegmentSizeBytes||8*1048576)/minUnit).toFixed(2).replace(/\.00$/,'');const speedUnit=1048576;$('#setSpeedUnit').value=String(speedUnit);$('#setSpeed').value=config.speedLimitBytesPerSec?(config.speedLimitBytesPerSec/speedUnit).toFixed(2).replace(/\.00$/,''):0;const a=config.appearance||{};$('#setFontFamily').value=a.fontFamily||'';$('#setFontSize').value=a.fontSizePercent||100;$('#setFontSizeRange').value=a.fontSizePercent||100;$('#setFontWeight').value=String(a.fontWeight||400);$('#setFontStyle').value=a.fontStyle||'normal';$('#setDensity').value=a.density||'balanced';$('#setAccent').value=a.accentColor||'#c9a46a';$('#setBackground').value=a.backgroundColor||'#070708';$('#setSurface').value=a.surfaceColor||'#0e0e11';$('#setTextColor').value=a.textColor||'#f2efe8';$('#setRadius').value=a.cornerRadius||14;$('#setReduceMotion').checked=!!a.reduceMotion;$('#setCustomCSS').value=a.customCSS||'';renderSettingsSpeedPresets();renderLocations();renderTuning()}
function collectSettings(){const speed=Math.max(0,Number($('#setSpeed').value)||0)*(Number($('#setSpeedUnit').value)||1048576);const minSeg=Math.max(.25,Number($('#setMinSegment').value)||8)*(Number($('#setMinSegmentUnit').value)||1048576);return{...config,downloadDir:$('#setDir').value.trim()||config.downloadDir,maxActive:Number($('#setActive').value)||3,maxPerHost:Number($('#setHost').value)||2,segmentsPerFile:Number($('#setSegments').value)||8,connectionsPerFile:Number($('#setConnections').value)||4,minSegmentSizeBytes:Math.round(minSeg),retries:Number($('#setRetries').value)||6,speedLimitBytesPerSec:Math.round(speed),launchMode:$('#setLaunch').value,appearance:appearanceFromUI()}}
async function saveSettings(){try{const d=await api('/api/v1/settings',{method:'POST',body:JSON.stringify(collectSettings())});config=d.config;engines=d.engines||engines;applyAppearance(config.appearance||{});runtimeConfigUI();renderEngineHealth();toast('Settings saved');return true}catch(e){toast(e.message,true);return false}}
async function saveSpeedLimit(bytes){try{const d=await api('/api/v1/settings',{method:'POST',body:JSON.stringify({...config,speedLimitBytesPerSec:Math.max(0,Math.round(bytes))})});config=d.config;engines=d.engines||engines;runtimeConfigUI();if(settingsOpen){$('#setSpeed').value=config.speedLimitBytesPerSec/Number($('#setSpeedUnit').value||1048576);renderSettingsSpeedPresets()}toast(config.speedLimitBytesPerSec?`Speed limited to ${speedLabel(config.speedLimitBytesPerSec)}`:'Speed limit removed')}catch(e){toast(e.message,true)}}

function renderEngineHealth(){const aria=engines?.aria2,dot=$('#engineDot'),text=$('#engineText');if(!dot||!text)return;if(aria?.available){text.textContent=`Native + aria2${aria.version?' '+aria.version:''}`;text.title=aria.managed?'aria2 managed by BoltDM':'External aria2 RPC';dot.style.background='var(--green)'}else{text.textContent='Native engine online';text.title=aria?.error?`aria2 unavailable: ${aria.error}`:'aria2 unavailable';dot.style.background='var(--green)'}}
function renderLocations(){const box=$('#locationList');if(!box)return;const list=tasks.filter(t=>t.state!=='completed');if(!list.length){box.innerHTML='<div class="empty-settings">No incomplete downloads to move.</div>';return}box.innerHTML=list.map(t=>{const movable=!t.engine||t.engine==='native';return`<div class="location-item"><div class="location-main"><div class="location-name">${esc(t.filename)}</div><div class="location-path" title="${esc(t.outputPath)}">${esc(t.outputRoot||dirOf(t.outputPath))}</div><div class="location-state">${esc(t.state)} · ${esc(t.engine||'native')}</div></div><button class="btn small" data-move-id="${t.id}" ${movable?'':'disabled title="Moving external-engine tasks is not implemented yet"'}>${movable?'Move…':'Engine-managed'}</button></div>`}).join('')}
function renderTuning(){const box=$('#tuningList');if(!box)return;const list=tasks.filter(t=>t.state!=='completed');if(!list.length){box.innerHTML='<div class="empty-settings">No current downloads to tune.</div>';return}box.innerHTML=list.map(t=>`<div class="tuning-item" data-tune-row="${t.id}"><div class="tuning-main"><div class="tuning-name">${esc(t.filename)}</div><div class="location-state">${esc(t.state)} · ${esc(t.engine||'native')} · current ${t.segments||'—'} seg / ${t.connections||'—'} conn</div></div><div class="tune-controls"><div class="mini-field"><label>Segments</label><input class="mini-input" data-tune-seg type="number" min="0" max="64" value="${Number(t.segmentSetting)||0}" placeholder="${config?.segmentsPerFile||8}"></div><div class="mini-field"><label>Connections</label><input class="mini-input" data-tune-conn type="number" min="0" max="32" value="${Number(t.connectionSetting)||0}" placeholder="${config?.connectionsPerFile||4}"></div><button class="btn small" data-tune-apply="${t.id}">Apply</button></div></div>`).join('')}
async function moveTask(id){const t=tasks.find(x=>x.id===id);if(!t)return;if(t.engine&&t.engine!=='native')return toast('Moving external-engine tasks is not implemented yet',true);try{const d=await api(`/api/v1/settings/pick-directory?initial=${encodeURIComponent(t.outputRoot||dirOf(t.outputPath))}`,{method:'POST'});toast(`Moving ${t.filename}…`);await api(`/api/v1/tasks/${id}/move`,{method:'POST',body:JSON.stringify({destination:d.path})});toast('Download moved and resume data preserved');await refresh();renderLocations()}catch(e){if(!/canceled/i.test(e.message))toast(e.message,true)}}
async function tuneTask(id,row){const segments=Number(row.querySelector('[data-tune-seg]').value)||0,connections=Number(row.querySelector('[data-tune-conn]').value)||0;try{await api(`/api/v1/tasks/${id}/tune`,{method:'POST',body:JSON.stringify({segments,connections,applyNow:true})});toast('Download settings applied');await refresh();renderTuning()}catch(e){toast(e.message,true)}}

async function refresh(){try{const d=await api('/api/v1/tasks');tasks=d.tasks||[];config=d.config;engines=d.engines||{};renderEngineHealth();runtimeConfigUI();render();if(settingsOpen){renderLocations();renderTuning()}}catch(e){$('#engineText').textContent='BoltDM offline';$('#engineDot').style.background='var(--red)'}}
async function action(id,act){if(act==='remove'){const t=tasks.find(x=>x.id===id);pendingRemoveId=id;$('#removeName').textContent=t?.filename||'this download';modal($('#removeModal'),true);return}try{await api(`/api/v1/tasks/${id}/${act}`,{method:'POST'});if(act==='open'||act==='reveal')return;if(act==='cancel')toast('Download canceled — it can still be resumed');await refresh()}catch(e){toast(e.message,true)}}
async function bulk(act,label){try{const d=await api(`/api/v1/bulk/${act}`,{method:'POST'});toast(`${label}: ${d.affected} download${d.affected===1?'':'s'}`);await refresh()}catch(e){toast(e.message,true)}}
function openAdd(){if(config)$('#addDir').value=config.downloadDir;$('#addUrl').value='';modal($('#addModal'),true);setTimeout(()=>$('#addUrl').focus(),80)}
async function pickDir(target,initial=''){try{const base=initial||target.value||config?.downloadDir||'';const d=await api(`/api/v1/settings/pick-directory?initial=${encodeURIComponent(base)}`,{method:'POST'});target.value=d.path}catch(e){if(!/canceled/i.test(e.message))toast(e.message,true)}}
function renderPresetButtons(container){container.innerHTML=[0,1,5,10,25,50,100,250].map(x=>{const v=x?x*1048576:0;return`<button class="preset" data-speed="${v}">${x?`${x} MB/s`:'Unlimited'}</button>`}).join('')}
function renderSettingsSpeedPresets(){renderPresetButtons($('#settingsSpeedPresets'));$$('#settingsSpeedPresets .preset').forEach(b=>b.classList.toggle('active',Number(b.dataset.speed)===Number(config?.speedLimitBytesPerSec||0)))}
